name: mattermost

instance_groups:
- name: mattermost
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - release: postgres
    name: postgres
    provides:
      db: {as: postgresql}
    properties:
      postgres:
        hba:
          - host all all 0.0.0.0/0 md5
          - host all all ::/0 md5
          - local all all trust
          - local all all trust
      pgpool:
        databases:
          - name: mattermost
            users:
              - admin
              - mattermost
            extensions: []
        users:
          - username: admin
            password: ((db-admin-password))
            admin:    true
          - username: mattermost
            password: ((db-mattermost-password))
  - release: mattermost
    name: mattermost
    consumes:
      postgresql: {from: postgresql}
    properties:
      mattermost:
        SqlSettings:
          AtRestEncryptKey: ((mattermost-sql-atrestencryptkey))
        ServiceSettings:
          SiteURL: ((mattermost-siteurl))
- name: sanity-test
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - release: mattermost
    name: sanity_test
    properties:
      mattermost:
        ServiceSettings:
          SiteURL: ((mattermost-siteurl))

variables:
- name: db-admin-password
  type: password
- name: db-mattermost-password
  type: password
- name: mattermost-sql-atrestencryptkey
  type: password
  options:
    length: 32

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: postgres
  sha1: dea5cad517c62afaf97a1b31df41ad691928d960
  url: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v2.0.0/postgres-2.0.0.tgz
  version: 2.0.0
- name: mattermost
  sha1: 8a1e1407312b642d078997e8a2235c28079f1b1f
  stemcell:
    os: ubuntu-xenial
    version: "250.58"
  url: https://s3.amazonaws.com/mattermost-boshrelease/compiled-releases/mattermost/mattermost-8.0.1-ubuntu-xenial-250.58-20190612-143543-265466551-20190612143557.tgz
  version: 8.0.1
